[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["python311Full"]

[build.nixpacksPlan.phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[deploy]
startCommand = "python run.py"
healthcheckPath = "/health"
healthcheckTimeout = 30
